// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4KdLYEO2wTr0bmxQ7Hb4sJgrrGHqsEo',
    appId: '1:987763566615:web:a66c8b4f53fd94204fd452',
    messagingSenderId: '987763566615',
    projectId: 'ecomm-75aef',
    authDomain: 'ecomm-75aef.firebaseapp.com',
    storageBucket: 'ecomm-75aef.firebasestorage.app',
    measurementId: 'G-DEXE7D13EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9vEco8rQt4NWcF-H9810M_rkzDaiA6E',
    appId: '1:987763566615:android:63af61c2614233974fd452',
    messagingSenderId: '987763566615',
    projectId: 'ecomm-75aef',
    storageBucket: 'ecomm-75aef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvz1aarTdJU5nct4TVlRdFx93CGiDBbE',
    appId: '1:987763566615:ios:ef193556125fdf364fd452',
    messagingSenderId: '987763566615',
    projectId: 'ecomm-75aef',
    storageBucket: 'ecomm-75aef.firebasestorage.app',
    iosBundleId: 'com.example.onboarding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvz1aarTdJU5nct4TVlRdFx93CGiDBbE',
    appId: '1:987763566615:ios:ef193556125fdf364fd452',
    messagingSenderId: '987763566615',
    projectId: 'ecomm-75aef',
    storageBucket: 'ecomm-75aef.firebasestorage.app',
    iosBundleId: 'com.example.onboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH4KdLYEO2wTr0bmxQ7Hb4sJgrrGHqsEo',
    appId: '1:987763566615:web:ca92ff8facbd0ff84fd452',
    messagingSenderId: '987763566615',
    projectId: 'ecomm-75aef',
    authDomain: 'ecomm-75aef.firebaseapp.com',
    storageBucket: 'ecomm-75aef.firebasestorage.app',
    measurementId: 'G-NYVXG9WF6R',
  );
}
